### ISSUE TITLE
Pipeline support

### ISSUE THREAD

**Issue by wdm0006** [marcotcr/lime#16] opened 2016-08-23 15:16 UTC
I was just reading through the new contributing guidelines and noticed two points:
1. Thinking through what is needed to use LIME in regression problems. An obvious problem is that features with different scales make it really hard to interpret.
2. Figuring out better alternatives to discretizing the data for tabular data. Discretizing is definitely more interpretable, but we may just want to treat features as continuous.

With @mrkaiser's recent PR now any regressor can be injected, including generic sklearn pipelines.  I suggest approaching the two points above by:
1. Break the discretizers out into a separate set of sklearn transformers (possibly a separate repo, as they would be useful outside of LIME as well). It would probably be easier to test/develop these as standalone transformers regardless of where they reside.  We can make it pretty configurable for different types of discretization or only discretizing certain columns.  It looks like it would be very similar to [category encoders](https://github.com/wdm0006/categorical_encoding).
2. Use sklearn pipelines for the regressors in LIME, which can include the discritizers and things like standard or robust scaling to address point (1).

**Comment by marcotcr** [comment] 2016-08-31 21:28
To your first suggestion, I have been thinking about how to organize the repository, since I have some new explanation methods, and would like to incorporate my submodular procedure (issue #11), which doesn't fit that well into LIME. I have to think carefully about that before I do anything though, so it's probably something for the next few months instead of weeks.

There are two ways of looking at explanations. They can either be contributions to the prediction (in which case we have to multiply the weight of the linear model with the feature value), or a model that approximates the underlying model in the neighborhood. Assume you have a feature k such that x_k = -1, and the local model approximation has w_k = 10. This feature has negative contribution and positive weight, and I don't know how to show these two things. This is a particular problem for regression problems, because I imagine you want to be able to make predictions about what would change if certain values were changed even more so than with classification. Also, the feature magnitudes and the weights really matter in regression (as opposed to in classification where the output is in the [0,1] range, which makes it simpler), which makes it even harder to interpret. A solution was showing weights in terms of standardized data, but that has its own problems for interpretation.

Discretizing obviously rids us of this problem, as contribution and weight become the same thing (since the feature becomes binary), but we lose information (and require some training data as well).

Anyway, I think we can definitely plug a regressor into LIME, but right now I don't think the result will be very interpretable (and thus useful). Plus, the prediction probability part of the visualization obviously assumes that the results will be in [0,1].

**Closed** 2016-11-12 22:11 UTC
